[package]
name = "oxysky"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.1.0"
oxysky_lib = { version = "0.1.0", path = "../oxysky_lib" }
tokio = { version = "1.38.0", features = ["full"] }

